Fixed KO_GENWAKU swap effect which never worked to any target.
HerculesWS/Hercules pull request #2831
Opened 2020-09-10 03:10 UTC by MrKeiKun

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This PR will fix KO_GENWAKU skill effect where there is a chance of you and your target swapping position.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2020-11-14 09:13 UTC, Kenpachi2k13 requested changes

2020-11-14 09:13 UTC, Kenpachi2k13 commented on src/map/skill.c
> +						if ( dstsd && pc_issit(dstsd) )
```suggestion
					if (!is_boss(bl) && unit->movepos(bl, x, y, 0, 0) != 0) {
						if (dstsd != NULL && pc_issit(dstsd))
```

2020-11-15 17:56 UTC, Kenpachi2k13 approved these changes

2020-11-16 23:54 UTC, MishimaHaruna approved these changes

2020-11-17 00:26 UTC, merged