Fix Freezing Spear on Watery Evasion
HerculesWS/Hercules pull request #2873
Opened 2020-10-17 06:20 UTC by MrKeiKun

…vasion.

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This fixes the damage buff effect of watery evasion when using freezing spear.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2020-10-17 10:23 UTC, Kenpachi2k13 requested changes

2020-10-17 10:23 UTC, Kenpachi2k13 commented on src/map/battle.c
> +					if (sc && sc->data[SC_NJ_SUITON])
```suggestion
					if (sc != NULL && sc->data[SC_NJ_SUITON] != NULL)
```

2020-10-17 18:12 UTC, Kenpachi2k13 approved these changes

2020-11-16 01:13 UTC, MishimaHaruna approved these changes

2020-11-16 01:22 UTC, merged