Fix nullpo error in searchstore
HerculesWS/Hercules pull request #2885
Opened 2020-10-30 00:34 UTC by guilherme-gm

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Fixes 2 checks in search store function:
1. it prevents trying to search with an empty item list, this is not even allowed by the client, and makes no sense in the process, as it always start the search by an item. (that's why I put the check on clif)

2. When searching for an item without asking for cards, it was giving us a nullpo because card_list would be NULL (as it becomes a "0-length array"), but it is a totally valid search (e.g. Searching for an ETC item would never have cards to check for). So I disabled the null pointer check when the card count is zero, from my tests and checking the code, every code called from this would check card count before trying to access the array, so it looks safe.

**Issues addressed:** 
None, i think

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2020-10-30 01:20 UTC, Kenpachi2k13 requested changes

2020-10-30 01:20 UTC, Kenpachi2k13 commented on src/map/clif.c
> +		return; // Should never happen
In my opinion this check should be placed some lines above, prior to assigning a value to `item_count`.

```c
	...

	if (packet_len < sizeof(struct PACKET_CZ_SEARCH_STORE_INFO))
	{// minimum packet length
		ShowError("clif_parse_SearchStoreInfo: Malformed packet (expected length=%u, length=%d, account_id=%d).\n", (uint32)sizeof(struct PACKET_CZ_SEARCH_STORE_INFO), packet_len, sd->bl.id);
		return;
	}

	if (p->itemsCount < 1) // Should never happen
		return;

	type       = p->searchType;
	max_price  = p->maxPrice;
	min_price  = p->minPrice;
	item_count = p->itemsCount;
	card_count = p->cardsCount;
	itemlist   = &p->items[0];

	...
```

2020-10-30 01:20 UTC, Kenpachi2k13 commented on src/map/searchstore.c
>  	nullpo_retv(itemlist);
I'd also check `item_count` prior to `nullpo_retv(itemlist);`.

```c
	if (item_count < 1) {
		clif->search_store_info_failed(sd, SSI_FAILED_NOTHING_SEARCH_ITEM);
		return;
	}

	nullpo_retv(itemlist);
```

2020-10-30 02:01 UTC, guilherme-gm commented
Thanks for reviewing it! fixed and rebased

2020-10-30 02:21 UTC, Kenpachi2k13 approved these changes

2020-10-30 03:30 UTC, 4144 approved these changes

2020-11-16 01:15 UTC, MishimaHaruna approved these changes

2020-11-16 01:48 UTC, merged