Water Screen Skill Fix
HerculesWS/Hercules pull request #2981
Opened 2021-04-12 10:20 UTC by MrKeiKun

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
While under Water Screen...
* It's master should now heal 1,000 HP every 10 seconds.
* All damage inflicted by it's master will be deflected to the Elemental Spirit(Aqua).

**Issues addressed:**

2021-04-14 18:02 UTC, EPuncker commented on src/map/status.c
> +
```suggestion
```

2021-04-27 04:32 UTC, EPuncker requested changes

2021-04-27 04:32 UTC, EPuncker commented on src/map/battle.c
> +	if ( ((d_tbl && sc && check_distance_bl(target, d_tbl, sc->data[SC_DEVOTION]->val3)) || e_tbl) && damage > 0 && skill_id != PA_PRESSURE && skill_id != CR_REFLECTSHIELD)
```suggestion
	if (((d_tbl && sc && check_distance_bl(target, d_tbl, sc->data[SC_DEVOTION]->val3)) || e_tbl) && damage > 0 && skill_id != PA_PRESSURE && skill_id != CR_REFLECTSHIELD)
```

2021-04-27 04:32 UTC, EPuncker commented on src/map/skill.c
> +		if( (!sc || (!sc->data[SC_DEVOTION] && skill_id != CR_REFLECTSHIELD && !sc->data[SC_WATER_SCREEN_OPTION])) && !shadow_flag)
```suggestion
		if((!sc || (!sc->data[SC_DEVOTION] && skill_id != CR_REFLECTSHIELD && !sc->data[SC_WATER_SCREEN_OPTION])) && !shadow_flag)
```

2021-04-27 04:32 UTC, EPuncker commented on src/map/skill.c
> +				if( !dmg.amotion )
```suggestion
				if(!dmg.amotion)
```

2021-05-05 17:22 UTC, MishimaHaruna approved these changes

2021-05-05 17:23 UTC, merged