Add reading and checking client flags
HerculesWS/Hercules pull request #3001
Opened 2021-05-06 18:21 UTC by 4144

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Client may send special flags in client_version field.
In this pr hercules will compare current server flags and client flags, and if flags different then client will be disconnected.
This will prevent from strange bugs if server or client was created with different features.

For now only supported feature flag is cash show with preview support.

Nemo patch will come soon...

2021-05-07 03:37 UTC, EPuncker requested changes

2021-05-07 03:37 UTC, EPuncker commented on conf/login/login-server.conf
> +		// Check is client flags same with compiled hercules version
```suggestion
		// Check if client flags are the same with compiled hercules version
```

2021-05-08 02:00 UTC, Jedzkie commented on conf/login/login-server.conf
> +		// Check is client flags same with compiled hercules version
@EPuncker maybe remove the word `the`?

2021-05-08 08:31 UTC, Samuel23 commented
@4144 Is it possible with this like cash shop changes?

If server side cash shop was reloaded and it when client opens the cash shop as it's not the same values with the reloaded server side it will be disconnected?

2021-05-08 11:18 UTC, 4144 commented
> @4144 Is it possible with this like cash shop changes?
> 
> If server side cash shop was reloaded and it when client opens the cash shop as it's not the same values with the reloaded server side it will be disconnected?

you want update cash shop after player connected to game?
then need send changed cash shop tabs to all players.

2021-05-08 13:44 UTC, Samuel23 commented
> > @4144 Is it possible with this like cash shop changes?
> > If server side cash shop was reloaded and it when client opens the cash shop as it's not the same values with the reloaded server side it will be disconnected?
> 
> you want update cash shop after player connected to game?
> then need send changed cash shop tabs to all players.

I created a custom @reloadcashdb to refresh cash shop items, the thing is it doesn't reload in game unless you relog in the game, so what happens is when I change anything in the server side and a player who doesn't relog yet, see's the old values which can lead to a mismatch for example price or item changes

2021-06-02 17:03 UTC, MishimaHaruna approved these changes

2021-06-02 17:03 UTC, merged