Update some guild related packets to use structures
HerculesWS/Hercules pull request #3016
Opened 2021-06-28 19:05 UTC by Asheraf

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2021-06-28 23:14 UTC, 4144 requested changes

2021-06-28 23:14 UTC, 4144 commented on src/map/packets_struct.h
> +#if PACKETVER < 20161026
0x0aa5 used from 2016-12-14bRagexe and 2016-11-30aRagexeRE

2021-06-28 23:14 UTC, 4144 commented on src/map/packets_struct.h
> +struct GUILD_MEMBER_INFO {
better put whole struct under ``#ifdef``

2021-06-28 23:14 UTC, 4144 commented on src/map/packets_struct.h
> +DEFINE_PACKET_HEADER(ZC_GUILD_INFO, 0x0a84);
0x0a84 exists from 2016-10-19aRagexe and 2016-09-21bRagexeRE

2021-06-28 23:14 UTC, 4144 commented on src/map/packets_struct.h
> +#if PACKETVER < 20160622
packet id probably better put near struct without additional ``#if``

2021-06-29 23:24 UTC, 4144 approved these changes

2021-07-07 19:27 UTC, MishimaHaruna approved these changes

2021-07-07 19:28 UTC, merged