Missing Rebellion config and db for Pre-RE
HerculesWS/Hercules pull request #3031
Opened 2021-08-12 09:51 UTC by MrKeiKun

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
This should make rebellion work in pre-re using renewal skill_db and sc_config.

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2021-08-12 17:13 UTC, 4144 requested changes

2021-08-12 17:13 UTC, 4144 commented on db/pre-re/skill_db.conf
> +	AfterCastActDelay: 1000
look like different formatting here and below

2021-08-13 11:49 UTC, 4144 approved these changes

2021-09-02 16:24 UTC, MishimaHaruna approved these changes

2021-09-02 16:40 UTC, merged