Fixed ignition break animation not showing on newer client.
HerculesWS/Hercules pull request #3034
Opened 2021-08-20 16:30 UTC by MrKeiKun

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
PR should fix the animation not showing on newer clients.

**Issues addressed:** #2511  

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2021-08-20 16:50 UTC, 4144 requested changes

2021-08-20 16:50 UTC, 4144 commented on src/map/skill.c
> +				case RK_IGNITIONBREAK:
look like different formatting?

2021-08-20 16:50 UTC, 4144 commented on src/map/skill.c
> +#if PACKETVER >= 20180207
if you not totally sure about packet version in all 3 supported clients, better add comment, ``unconfirmed``

2021-09-02 17:38 UTC, MishimaHaruna approved these changes

2021-09-02 17:39 UTC, merged