Fixed multiple VS compiler warning
HerculesWS/Hercules pull request #3058
Opened 2021-10-06 08:44 UTC by MrKeiKun

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2021-10-06 10:11 UTC, MrKeiKun commented
_Ignore the branch name_

2021-10-06 11:40 UTC, Asheraf requested changes

2021-10-06 11:40 UTC, Asheraf commented on src/map/clif.h
> +	void (*updatestatus) (struct map_session_data *sd, enum type);
`enum status_point_types`

2021-10-06 11:47 UTC, MrKeiKun commented on src/map/clif.h
> +	void (*updatestatus) (struct map_session_data *sd, enum type);
holy crap. nice catch!

2021-10-06 12:07 UTC, MrKeiKun commented on src/map/clif.h
> +	void (*updatestatus) (struct map_session_data *sd, enum status_point_types);
have to replace the ctrl key after this, stuck on multi selection :|

2021-10-06 12:35 UTC, Asheraf commented on src/map/clif.c
> +		if (sd->inventory_data[index] != NULL)
this is already being checked few lines above, you can probably replace both checks with a nullpo_retv under the assert.

2021-10-30 12:09 UTC, 4144 approved these changes

2021-11-02 16:33 UTC, MishimaHaruna approved these changes

2021-11-02 18:42 UTC, merged