Update packets for all client types
HerculesWS/Hercules pull request #3082
Opened 2021-11-05 16:02 UTC by 4144

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Update packets for latest ragexe, ragexeRE, ragexe zero.
Add basic support for grade levels.
Add new zero ui packets, commands and demo script.
Add unequip all at command and packets.

2021-11-05 16:06 UTC, dastgirp commented on doc/script_commands.txt
> +*prompt("<option>"{, "<option>", ...})
I think you meant *zprompt* here

2021-11-05 16:11 UTC, 4144 commented on doc/script_commands.txt
> +*prompt("<option>"{, "<option>", ...})
yes, thanks

2021-11-05 17:24 UTC, EPuncker commented on sql-files/main.sql
> +  `grade` TINYINT UNSIGNED NOT NULL DEFAULT '0',
```suggestion
	`grade` TINYINT UNSIGNED NOT NULL DEFAULT '0',
```

2021-12-01 00:43 UTC, MishimaHaruna requested changes

2021-12-01 00:43 UTC, MishimaHaruna commented on src/map/packets.h
> +#if PACKETVER >= 29191224
Is this meant to be 2919 or 2019?

2021-12-01 00:43 UTC, MishimaHaruna commented on doc/script_commands.txt
> +*zmes1("<string>")
Can you also add a mention of the `zmes1f()`/`zmes2f()` variants, so that someone searching this file for them will find a match?

2021-12-01 19:56 UTC, MishimaHaruna approved these changes

2021-12-01 21:01 UTC, merged