Implement Grade Enchant User Interface
HerculesWS/Hercules pull request #3100
Opened 2021-12-27 14:48 UTC by Asheraf

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

This PR adds support for Grade Enchanter.
![image](https://user-images.githubusercontent.com/14294215/147482459-04d8475c-1b46-449e-9a5d-7accd91023cb.png)

The missing parts:

- Values in the database are not official and I just guessed them.
- Item protection for older clients is not supported

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2021-12-27 15:31 UTC, 4144 requested changes

2021-12-27 15:31 UTC, 4144 commented on src/map/clif.c
> +	nullpo_retv(sd);
missing nullpo check for ``gi``

2021-12-27 15:31 UTC, 4144 commented on src/map/grader.c
> +	nullpo_ret(source);
missing check for nullpo for ``gm``

2022-01-05 16:00 UTC, MishimaHaruna requested changes

2022-01-05 18:22 UTC, Asheraf commented on src/map/log.c
> +		case LOG_TYPE_GRADE:            return '4';  // Grade Enchant
Added to picklog and provided an update sql file.

2022-01-05 22:32 UTC, MishimaHaruna approved these changes
I also added the type '4' to the zenylog table since there's a `pc->payzeny()` call with the `LOG_TYPE_GRADE` type

2022-01-05 22:33 UTC, merged