Updated script_commands
HerculesWS/Hercules pull request #3177
Opened 2022-12-05 17:55 UTC by EPuncker

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
- fixed several typos
- removed mob_avail related stuff as it doesn't exist anymore
- fixed file extension in references
- updated options with new values/entries
- added website for real time regex testing

**Issues addressed:** 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2022-12-05 17:56 UTC, EPuncker commented
@MishimaHaruna also I would like to know if updating scripts_commands from txt to markdown format would be welcome in a future PR?

2022-12-05 17:58 UTC, Asheraf requested changes

2022-12-05 17:58 UTC, Asheraf commented on doc/constants_pre-re.md
> +## Skills (db/pre-re/skill_db.conf)
These are auto generated files you should not change them manually but rather update the code in `plugins/constdb2doc.c`

2022-12-07 19:17 UTC, MishimaHaruna approved these changes

2022-12-08 18:31 UTC, merged