Added config option to keep direction for free cells
HerculesWS/Hercules pull request #3242
Opened 2023-10-29 02:54 UTC by csnv

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

Added configuration option `keep_dir_free_cell`. Although it is set to false, I would like it to be enabled by default in Hercules.
This option allows discovery of free cells based on the unit's current facing direction instead of always using EAST, which have the following advantages:
- Improves distribution of mobs when dispersing after being grouped. This setting allows monsters to spread in a circular fashion instead of forming a long horizontal line.
- Allows characters to move more naturally if they came from the east, instead of walking back.
- In some instances, fixes issue #1241 allowing the user to obtain the item.

This commit also fixes #1241 in all scenarios not allowing the character to enter a walk loop. Fix based on rAthena's.

**Issues addressed:** 
#1241 

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2023-10-29 05:12 UTC, skyleo commented
Love the idea!

2023-10-29 05:20 UTC, skyleo requested changes

2023-10-29 05:20 UTC, skyleo commented on src/map/clif.c
> +	RFIFOPOS(fd, packet_db[RFIFOW(fd, 0)].pos[0], &x, &y, NULL);
Can you separate this change to its own commit as it doesn't do what your commit message states?

2023-10-30 04:04 UTC, skyleo approved these changes

2023-11-05 00:58 UTC, 4144 approved these changes

2023-11-19 18:17 UTC, MishimaHaruna approved these changes

2023-11-19 23:14 UTC, merged