Fix copying own skills via RG_PLAGIARISM or SC_REPRODUCE causing the skill to be deleted and skills that required it eventually.
HerculesWS/Hercules pull request #3298
Opened 2024-05-25 17:13 UTC by skyleo

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed

We address this by implementing logic to use SKILL_FLAG_REPLACED_LV_0 in SC_REPRODUCE and RG_PLAGIARISM.
We also reduced some code-duplication shared with pc_jobchange and skill_attack logic of those two skills.
SKILL_FLAG_PERM_GRANTED skills are no longer copyable as there's no clearly defined implementation for those when copied.

**Issues addressed:** #3289

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2024-05-30 15:37 UTC, guilherme-gm requested changes
I think there is some missing packet (at least for "newer" clients), on 2019-12-24 main, when a new skill is copied by Plagiarism (Rogue one) the old one stays in the tree as "unlearned":

![image](https://github.com/HerculesWS/Hercules/assets/10552039/43ffe761-d0ac-4370-8aa6-d594d7f0287b)

In this example, I plagiarized Magnum Break and then Bash. Magnum Break stays there as disabled until I log out.

This does not happen in master, so I am guessing it is a bug.

2024-05-30 17:57 UTC, skyleo commented
> I think there is some missing packet (at least for "newer" clients), on 2019-12-24 main, when a new skill is copied by Plagiarism (Rogue one) the old one stays in the tree as "unlearned":


Did you test this on a rogue / stalker and a character that doesn't own skills outside of his skill tree (such as GMs with all skills)

2024-05-30 20:40 UTC, guilherme-gm commented
Hmm I did use `@allskills` (using default herc configs, where only my class skill tree gets filled -- so no extra skill in my character).

My test was more or less like that:
- `@job Shadow Chaser T.`
- `@allskills`

then, on a pvp map, use another character to hit me with Magnum Break, which got copied. Then hit by Bash, which got copied but did not erase Magnum Break there.

2024-05-30 21:06 UTC, skyleo commented
> Hmm I did use `@allskills` (using default herc configs, where only my class skill tree gets filled -- so no extra skill in my character).
> 
> My test was more or less like that:
> 
>     * `@job Shadow Chaser T.`
> 
>     * `@allskills`
> 
> 
> then, on a pvp map, use another character to hit me with Magnum Break, which got copied. Then hit by Bash, which got copied but did not erase Magnum Break there.

Please don't test stuff like this with `@allskills`, try to test it on a somewhat realistic character. `@job` and `@jlvl` should be enough.

If you can reproduce that way I'll try to research.

2024-05-31 00:58 UTC, skyleo commented
Problem discovered, fixed and accordingly rebased the commits. Introducing a new function `pc->is_own_skill` now as first commit.

2024-05-31 01:04 UTC, skyleo commented on src/map/skill.c
>  	if (!cidx)
Kinda lazy :(

2024-05-31 01:32 UTC, guilherme-gm approved these changes
working fine now; even with `allskills`

2024-06-30 17:14 UTC, MishimaHaruna approved these changes

2024-06-30 17:14 UTC, merged