Enhance athena-start by Haru
HerculesWS/Hercules pull request #3299
Opened 2024-05-26 17:31 UTC by xTararAisx

### Added API Server Support and Enhanced Logging and Portability

- **Add API Server Variable**: Included the `A_SRV=api-server` variable to manage the API server alongside the existing login, char, and map servers.
- **Enhanced Process Checking**: Replaced `ps aux` with `pgrep` in the `isrunning` function to improve portability across different Unix-like systems.
- **Ensure Logs Directory Exists**: Added a check and creation step for the `logs` directory within the `do_start` function to ensure log files can be created without errors.
- **Redirect Output to Log Files**: Modified the `do_start` function to redirect the output of each server process to individual log files located in the `./logs` directory for easier debugging.
- **Include API Server in Stop Function**: Updated the `do_stop` function to include the API server, ensuring it gets properly terminated along with the other server components.
- **Include API Server in Status Function**: Updated the `do_status` function to include the API server, providing status checks for all server components.
- **Add API Server to Main Case Statement**: Modified the main case statement to include the API server in the start, stop, restart, and status commands.

Please review these changes and consider merging them into the main project. Thank you!

2024-05-27 12:00 UTC, jasonch35 requested changes

2024-05-27 13:38 UTC, xTararAisx commented on athena-start
> +	printf "${echo_bold_green}%-15s${echo_normal} ${echo_bold}http://hercules.ws/${echo_normal}\n" "Website/Forum:"
ups! done thing! :)

2024-05-28 10:57 UTC, jasonch35 commented
I used this for 3 days now. Here are my comments:

1. Herc already has `log` directory, can we save it there instead of making new `logs`?
2. Error, debug, and warning show messages are not showing as it should like Haru said
3. Maybe rename to `herc-start`? 😄

2024-05-31 01:36 UTC, skyleo commented
> Thanks for the update! Ive fixed it and enhance it even further
> 
>     * Add optional arguments `--display-error-off` and `--display-error-on` to control error display.
> 
>     * Set error display to ON by default.
> 
>     * Update usage message to reflect new arguments.
> 
>     * Use existing Hercules log directory (`../log`) instead of creating a new one.
> 
>     * Clean and fix issues in `do_start`, `do_stop`, and `do_status` functions.
> 
>     * Ensure proper termination and status checking of processes.
> 
>     * Improve argument parsing for better user experience.

Those are really nice points. Perfect for individual commits using exactly these messages. Please use atomic commits. If you have to make a bullet list to describe the changes of one commit then it's meant to be multiple commits.

2024-05-31 09:45 UTC, xTararAisx commented
huh? what?

2024-05-31 23:40 UTC, guilherme-gm commented
What skyleo mentioned is that having huge commits doing lots of things at once is not a good idea. You listed several additions, they would be better being separate commits, so your changes are built step by step. Easier to review, easier to find bugs now and in the future.

Smaller commits allows us to see things like: I am reading a commit that says "I added X", and could think "Uh, why is it doing Y? -- oh this is a bug!"; in the future it would also be easier if we are wondering why something is there.

Right now, if we look at the commit history of your PR, we see:
- Update athena-start
- - Update athena-start
- - Update athena-start

I think those links may help you get started with rebasin

2024-05-31 23:49 UTC, guilherme-gm commented
What skyleo mentioned is that having huge commits doing lots of things at once is not a good idea. You listed several additions, they would be better being separate commits, so your changes are built step by step. Easier to review, easier to find bugs now and in the future.

Smaller commits allows us to see things like: I am reading a commit that says "I added X", and could think "Uh, why is it doing Y? -- oh this is a bug!"; in the future it would also be easier if we are wondering why something is there.

Right now, if we look at the commit history of your PR, we see:
- Update athena-start
   - lots of things happened here
- Update athena-start
   - lots of things happened here
- Update athena-start
   - lots of things happened here
- ...

We have many changes coming at once, even if they are detailed in the commit body, they seem like a lot of unrelated changes happening at once. It would be better to have them as separate commits, like:

```
commit 1: Add optional arguments `--display-error-off` and `--display-error-on` to control error display.
commit 2: Set error display to ON by default.
commit 3: Update usage message to reflect new arguments.
commit 4: Use existing Hercules log directory (`../log`) instead of creating a new one.
// ...
```

I think those links may help you get started with a bit more info about why we are asking that and getting started with rebasing to split commits:
- https://dev.to/karaluton/a-guide-to-perfecting-pull-requests-2b66
- https://github.com/supercollider/supercollider/wiki/Rebasing-a-PR#rearranging-combining-commits-or-editing-commit-messages-with-rebase

2024-06-01 10:24 UTC, closed without merging