`getmobdrops` refactor
HerculesWS/Hercules pull request #3319
Opened 2024-09-10 19:34 UTC by jasonch35

### Pull Request Prelude

- [x] I have followed [proper Hercules code styling][code].
- [x] I have read and understood the [contribution guidelines][cont] before making this PR.
- [x] I am aware that this PR may be closed if the above-mentioned criteria are not fulfilled.

### Changes Proposed
Avoid use of global variables that tend to get overwritten when command is called by 2 or more players simultaneously.
The command now requires an array as the second or third argument.
The third argument is optional and, if provided, will copy the drop rates into the array.
Updated documentation to reflect these changes.

Usage:
```
.@count = getmobdrops(.@mob_id, .@item, .@rate);
if (.@count) {
	mes(getmonsterinfo(.@mob_id, MOB_NAME) + " - " + .@count + " drops found:");
	for (.@i = 0; .@i < .@count; ++.@i) {
		mes(.@item[.@i] + " (" + getitemname(.@item[.@i]) + ") " + .@rate[.@i]/100 + ((.@rate[.@i]%100 < 10) ? ".0":".") + .@rate[.@i]%100 + "%");
	}
} else {
	mes("No drops found.");
}
close();
```

**Issues addressed:** 
Wrong data when multiple players call the command.

[cont]: https://github.com/HerculesWS/Hercules/blob/master/CONTRIBUTING.md
[code]: https://github.com/HerculesWS/Hercules/wiki/Coding-Style

2024-09-17 13:00 UTC, skyleo commented
May want to consider to deprecate the command instead, to not screw over existing scripts too much. And instead use a new name `getmonsterdrops`, so that when the deprecated command is used, a warning is shown on map-server saying to use `getmonsterdrops` instead.

Alternatively one can go the hard-route but you really have to ensure and be aware of what is shown to people using older scripts then, it has to not silently fail 100%. And it definitely would be good if it fails at parsing already and not at runtime, otherwise people may start the server and think all is fine after the update containing this change.

Ideally this PR should already replace all existing scripts with the new command.

2024-09-18 17:17 UTC, jasonch35 commented
@skyleo Good point, I hadn’t considered that. However, both [getpartymember](https://github.com/HerculesWS/Hercules/pull/3315) and [getguildmember](https://github.com/HerculesWS/Hercules/pull/3318) underwent similar upgrades and were merged without deprecation. 😄 Should I still create a new command and deprecate getmobdrops?

2024-09-21 05:45 UTC, skyleo commented
> @skyleo Good point, I hadn’t considered that. However, both [getpartymember](https://github.com/HerculesWS/Hercules/pull/3315) and [getguildmember](https://github.com/HerculesWS/Hercules/pull/3318) underwent similar upgrades and were merged without deprecation. 😄 Should I still create a new command and deprecate getmobdrops?

Although I don't fully remember the behavior, there scripting engine may fail older scripts on parsing already due to the mandatory parameter amount being different between the older and your version of the script command.

So I guess you may be fine. May be worth testing though. ;)

2024-09-24 09:33 UTC, skyleo approved these changes

2024-09-28 22:09 UTC, MishimaHaruna commented
> Although I don't fully remember the behavior, the script engine may fail older scripts on parsing already due to the mandatory parameter amount being different between the older and your version of the script command.

That's right, since the old command had only one argument and the new one has two mandatory ones and an optional one, it'll already error out when trying to load an old script, forcing the user to notice and update the script. There's no need to deprecate and renamed the command in this case

2024-09-29 02:18 UTC, MishimaHaruna requested changes

2024-09-29 02:18 UTC, MishimaHaruna commented on doc/script_commands.txt
> +	if (.@count) {
Small nitpick in order to encourage the readers of this documentation to use better code style

```suggestion
	if (.@count == 0) {
```

2024-09-29 02:18 UTC, MishimaHaruna commented on src/map/script.c
> +	const char *varname1 = reference_getname(data1);
This is a dangerous operation on data that might not be a reference (might cause a crash depending on the value passed). Please only call `reference_getname()` after ensuring that `data_isreference()`.

2024-09-29 02:18 UTC, MishimaHaruna commented on src/map/script.c
> +	int varid2;
Might be safer to initialize these even if they are not used in some cases

```suggestion
	const char *varname2 = NULL;
	int varid1 = reference_getid(data1);
	int varid2 = 0;
```

2024-09-29 02:18 UTC, MishimaHaruna commented on src/map/script.c
> +		varname2 = reference_getname(data2);
Same remark as above about calling `reference_getname()` before checking whether `data_isreference()`

2024-10-26 16:04 UTC, MishimaHaruna approved these changes
Thank you, looks good to me now, I'll merge it

2024-10-26 16:05 UTC, merged